# Generated by Django 5.2.13 on 2026-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0002_remove_profile_bio_remove_profile_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Administrator', 'Administrator')], default='Staff', max_length=20),
        ),
    ]
