# Generated by Django 5.2.13 on 2026-04-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0005_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
