# Generated by Django 5.2.13 on 2026-05-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0006_remove_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
