# Generated by Django 5.2.13 on 2026-05-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0008_event_attendanceentry_qrsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='check_in_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/check_in/'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='check_out_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/check_out/'),
        ),
    ]
