# Generated by Django 5.2.13 on 2026-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0009_attendanceentry_check_in_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
